learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL pattersn for learning_logs."""

from django.urls import path

from . import views

app_name = "learning_logs"

urlpatterns = [
	# Home page
	path('', views.index, name='index'),

	# Show all topics
	path('topics/', views.topics, name='topics'),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	"""A topic the user is learning about."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		"""Return a  string representation of the model."""
		return self.text


class Entry(models.Model):
	"""Something specific learned about a topic"""
	topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Return a  string representation of the model."""
		if len(self.text) > 50:
			return self.text[:50] + "..."
		else:
			return self.text

learning_logs/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.
def index(request):
	"""The homepage for Learning Log"""
	return render(request, 'learning_logs/index.html')

def topics(request):
	"""Show all topics."""
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)

learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Learning Log</a> -
	<a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<h1>Learning Log</h1>

	<p>
		Learning Python is so much fun!
	</p>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topics</p>

<ul>
	{% for topic in topics %}
		<li>{{ topic }}</li>
	{% empty %}
		<li>No topics have been added yet.</li>
	{% endfor %}
</ul>

{% endblock content %}